[package]
name = "venum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
chrono = "0.4"
rust_decimal = "1.22"
rust_decimal_macros = "1.22"
